<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
	public function getAllCategories(){
    	$allCategoriesResult = $this->createQueryBuilder('post')
			->select('c.id, c.name')->distinct()
            ->join('post.category', 'c')
			->getQuery()
			->getResult();
        $allCategories = array();
        foreach ($allCategoriesResult as $index => $data) {
            $allCategories[$data['id']] = $data['name'];
        }
        return $allCategories;
    }

 	/**
 	 * Converts a doctrine row result array into a flat array
 	 */
    private function _flatten(Array $array){
    	$flattenedArray = array();
    	array_walk_recursive($array, function($a) use (&$flattenedArray) { $flattenedArray[] = $a; });
    	return $flattenedArray;
    }
}
